import Providers from './providers';
import { Header } from './components/Layout/Header/Header';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<Providers>
          {/* @ts-expect-error Server Component */}
          <Header/>
          {children}
        </Providers>
			</body>
		</html>
	);
}
